# single test suite, non-parallel build.

env:
  global:
    - CC_TEST_REPORTER_ID=9ca5813bd5f4675d95d88838494ead8f435d60c0cd4570387129adb0740e769c
language: java
jdk:
  - oraclejdk9
  sudo: false
before_install:
  - nvm install 0.12
  - nvm use 0.12  # forzamos el uso de node 0.12
  - npm install -g grunt-cli
  - npm install -g bower
  - bower install
install:
  - npm install
  - mvn clean test
branches:
  only: master
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

